#!/usr/local/bin/ruby

require './compiler/compiler.rb'
require 'optparse'

options = { mode: :compile }
OptionParser.new do |opts|
  opts.banner = "Usage: ./compile infile.m- [options]"

  opts.on("-m [MODE]", "--mode [MODE]", [:parse, :ast, :compile], "Select mode (lex, parse, ast, compile), default is compile") do |mode|
    options[:mode] = mode
  end

  opts.on("-s", "--silent", "Supress all output") do |mode|
    options[:silent] = true
  end
end.parse!

Compiler.compile ARGV.first, options
