describe Compiler do
  context "#compile" do
    before do
      @file_double = double(File)
      @filename = 'foobar.baz'
      allow(File).to receive(:open).with(@filename).and_return(@file_double)
      allow(@file_double).to receive(:read)
      # make sure it's always always always closed
      expect(@file_double).to receive(:close)
    end

    it "lexes from a file" do
      expect(@file_double).to receive(:read)
      Compiler.compile @filename
    end

    it "closes the file if the read operation fails" do
      some_error = ArgumentError.new('some error message generated by File.read')
      allow(@file_double).to receive(:read).and_raise some_error
      expect{ Compiler.compile @filename }.to raise_error(some_error)
    end

    it "prints the result" do
      content = "Some\nmulti\nline\nstuff"
      allow(@file_double).to receive(:read).and_return content 
      expect{ Compiler.compile @filename }.to output.to_stdout
    end
  end
end
